[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  REMOVE_BG_API_KEY = "HEbMXANwLV5B7fe4c6ouNimb"
  FREE_LIMIT_DISABLED = "1"
  NODE_VERSION = "20"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  node_bundler = "esbuild"

[context.production]
  environment = { REMOVE_BG_API_KEY = "HEbMXANwLV5B7fe4c6ouNimb", FREE_LIMIT_DISABLED = "1", NODE_VERSION = "20", NETLIFY_NEXT_PLUGIN_SKIP = "true" }

[context.deploy-preview]
  environment = { REMOVE_BG_API_KEY = "HEbMXANwLV5B7fe4c6ouNimb", FREE_LIMIT_DISABLED = "1", NODE_VERSION = "20", NETLIFY_NEXT_PLUGIN_SKIP = "true" }

[context.branch-deploy]
  environment = { REMOVE_BG_API_KEY = "HEbMXANwLV5B7fe4c6ouNimb", FREE_LIMIT_DISABLED = "1", NODE_VERSION = "20", NETLIFY_NEXT_PLUGIN_SKIP = "true" }
